### ISSUE TITLE
[Bug] 对仅安装fabric的版本的fabric loader无法进行更新

### ISSUE THREAD

**Issue by Schwarz0079** [burningtnt/HMCL#6]
### 平台 | Platform

Win11

### 问题描述 | Problem Description

在一个安装有老版本Fabric和fabric API的版本上（BUG触发于1.20.1）先更新fabric api之后启动一次游戏 崩溃后在HMCL的对应版本的自动安装界面点击更新图标并选择最新版 之后弹出安装失败 暂不支持opt,fabric或opt,forge同时安装在MC1.13及以上版本

### 启动器崩溃报告 / 启动器日志文件 | Launcher Crash Report / Launcher Log File

[hmcl-exported-logs-2024-04-29T21-07-29.log](https://github.com/burningtnt/HMCL/files/15149567/hmcl-exported-logs-2024-04-29T21-07-29.log)

**Comment by zkitefly** [comment]
你是不是发错了？这个是 @burningtnt 的 fork hmcl 仓库

请到 https://github.com/HMCL-dev/HMCL/issues 发送反馈，谢谢

**Comment by zkitefly** [comment]
https://github.com/burningtnt/HMCL/blob/82d5306497e6ba38f4dd61ddcc39b60e70a117ee/HMCLCore/src/main/java/org/jackhuang/hmcl/download/fabric/FabricInstallTask.java#L67

这里出了问题

**Comment by burningtnt** [comment]
这个问题已经修复了，是低版本 HMCL 污染了版本 JSON。已经向当事人在用户群解答
